# Canonical list of Ecuadorian academic repositories targeted for YACHAQ-LLM
# Each entry includes scraping instructions and storage hints.
# Generated: 2025-10-18

meta:
  maintainer: "Yachaq Data Platform"
  s3_prefix: "s3://yachaq-lex-data-bucket-<suffix>/raw/ecuador_academia"
  harvesting_note: "Process one source per run; prefer OAI-PMH when available."

repositories:
  - institution: "Universidad Central del Ecuador"
    short_code: "UCE"
    platform: "DSpace"
    repository: "Repositorio Digital UCE"
    url: "https://www.dspace.uce.edu.ec/"
    access: "Open"
    content: ["thesis", "research_papers", "institutional_publications"]
    harvest:
      method: "oai-pmh"
      base_url: "https://www.dspace.uce.edu.ec/oai/request"
      notes: "Use sets per faculty; throttle to 1 req/sec."
    storage:
      prefix: "uce"

  - institution: "Escuela Politécnica Nacional"
    short_code: "EPN"
    platform: "DSpace"
    repository: "Repositorio Digital EPN"
    url: "https://bibdigital.epn.edu.ec/"
    access: "Open"
    content: ["thesis", "research_projects", "scientific_publications"]
    harvest:
      method: "oai-pmh"
      base_url: "https://bibdigital.epn.edu.ec/oai/request"
      notes: "Filter for dissertations; capture engineering keywords."
    storage:
      prefix: "epn"

  - institution: "Escuela Superior Politécnica del Litoral"
    short_code: "ESPOL"
    platform: "DSpace"
    repository: "DSpace ESPOL"
    url: "https://www.dspace.espol.edu.ec/"
    access: "Open"
    content: ["undergrad_thesis", "grad_thesis", "research"]
    harvest:
      method: "scrapy"
      entrypoint: "https://www.dspace.espol.edu.ec/handle/123456789/1"
      notes: "Infinite scroll requires Selenium; fall back to OAI at /oai/request."
    storage:
      prefix: "espol"

  - institution: "Universidad de Cuenca"
    short_code: "UCUENCA"
    platform: "DSpace"
    repository: "Repositorio Digital UCUENCA"
    url: "https://dspace.ucuenca.edu.ec/"
    access: "Open"
    content: ["thesis", "dissertations", "research_articles"]
    harvest:
      method: "oai-pmh"
      base_url: "https://dspace.ucuenca.edu.ec/oai/request"
      notes: "Use resumption tokens; translate faculty tags."
    storage:
      prefix: "ucuenca"

  - institution: "Universidad Técnica de Ambato"
    short_code: "UTA"
    platform: "DSpace"
    repository: "Repositorio Digital UTA"
    url: "https://repositorio.uta.edu.ec/"
    access: "Open"
    content: ["graduation_projects", "thesis"]
    harvest:
      method: "oai-pmh"
      base_url: "https://repositorio.uta.edu.ec/oai/request"
      notes: "Map degree metadata to taxonomy."
    storage:
      prefix: "uta"

  - institution: "Universidad Nacional de Loja"
    short_code: "UNL"
    platform: "DSpace"
    repository: "Repositorio Digital UNL"
    url: "https://dspace.unl.edu.ec/"
    access: "Open"
    content: ["thesis", "research_projects"]
    harvest:
      method: "oai-pmh"
      base_url: "https://dspace.unl.edu.ec/oai/request"
      notes: "Focus on agricultural sciences collections."
    storage:
      prefix: "unl"

  - institution: "Universidad Técnica del Norte"
    short_code: "UTN"
    platform: "DSpace"
    repository: "Repositorio Digital UTN"
    url: "https://repositorio.utn.edu.ec/"
    access: "Open"
    content: ["thesis", "research_articles"]
    harvest:
      method: "oai-pmh"
      base_url: "https://repositorio.utn.edu.ec/oai/request"
      notes: "Set retry limit to 3; some records exceed 50 MB."
    storage:
      prefix: "utn"

  - institution: "Universidad Politécnica Salesiana"
    short_code: "UPS"
    platform: "DSpace"
    repository: "Repositorio Institucional UPS"
    url: "https://dspace.ups.edu.ec/"
    access: "Open"
    content: ["research", "thesis", "learning_resources"]
    harvest:
      method: "scrapy"
      entrypoint: "https://dspace.ups.edu.ec/handle/123456789/1"
      notes: "Community taxonomy requires recursive crawling; capture license field."
    storage:
      prefix: "ups"

  - institution: "Universidad Católica de Santiago de Guayaquil"
    short_code: "UCSG"
    platform: "DSpace"
    repository: "Repositorio Digital UCSG"
    url: "http://repositorio.ucsg.edu.ec/"
    access: "Open"
    content: ["thesis", "research_papers", "legal_studies"]
    harvest:
      method: "selenium"
      entrypoint: "http://repositorio.ucsg.edu.ec/handle/3317/1"
      notes: "Site uses legacy JS pagination; enable headless Chrome."
    storage:
      prefix: "ucsg"

  - institution: "Universidad Técnica de Machala"
    short_code: "UTMACH"
    platform: "DSpace"
    repository: "Repositorio Digital UTMACHALA"
    url: "http://repositorio.utmachala.edu.ec/"
    access: "Open"
    content: ["thesis", "teaching_materials", "research"]
    harvest:
      method: "oai-pmh"
      base_url: "http://repositorio.utmachala.edu.ec/oai/request"
      notes: "Check SSL fallback; site may redirect to http."
    storage:
      prefix: "utmach"

  - institution: "Universidad Técnica Particular de Loja"
    short_code: "UTPL"
    platform: "DSpace"
    repository: "Repositorio Institucional UTPL"
    url: "https://dspace.utpl.edu.ec/"
    access: "Open"
    content: ["learning_objects", "research", "thesis"]
    harvest:
      method: "oai-pmh"
      base_url: "https://dspace.utpl.edu.ec/oai/request"
      notes: "Capture language metadata (es/en)."
    storage:
      prefix: "utpl"

  - institution: "Universidad San Francisco de Quito"
    short_code: "USFQ"
    platform: "DSpace"
    repository: "Repositorio Digital USFQ"
    url: "https://repositorio.usfq.edu.ec/"
    access: "Open"
    content: ["thesis", "dissertations", "faculty_research"]
    harvest:
      method: "oai-pmh"
      base_url: "https://repositorio.usfq.edu.ec/oai/request"
      notes: "Ensure persistent identifiers stored in manifest."
    storage:
      prefix: "usfq"

  - institution: "Universidad Andina Simón Bolívar"
    short_code: "UASB"
    platform: "DSpace"
    repository: "UASB-Digital"
    url: "https://repositorio.uasb.edu.ec/"
    access: "Open"
    content: ["masters_thesis", "doctoral_thesis", "institutional_publications"]
    harvest:
      method: "oai-pmh"
      base_url: "https://repositorio.uasb.edu.ec/oai/request"
      notes: "Tag social sciences vs law collections; include abstract language."
    storage:
      prefix: "uasb"

  - institution: "Pontificia Universidad Católica del Ecuador"
    short_code: "PUCE"
    platform: "DSpace"
    repository: "Repositorio Digital PUCE"
    url: "https://repositorio.puce.edu.ec/"
    access: "Open"
    content: ["thesis", "research_articles", "publications"]
    harvest:
      method: "oai-pmh"
      base_url: "https://repositorio.puce.edu.ec/oai/request"
      notes: "Large PDFs; enable chunked downloads via requests."
    storage:
      prefix: "puce"

  - institution: "FLACSO Ecuador"
    short_code: "FLACSO"
    platform: "DSpace"
    repository: "Repositorio FLACSO Andes"
    url: "https://repositorio.flacsoandes.edu.ec/"
    access: "Open"
    content: ["books", "working_papers", "journals"]
    harvest:
      method: "oai-pmh"
      base_url: "https://repositorio.flacsoandes.edu.ec/oai/request"
      notes: "Capture Creative Commons license field."
    storage:
      prefix: "flacso"

  - institution: "Instituto de Altos Estudios Nacionales"
    short_code: "IAEN"
    platform: "DSpace"
    repository: "Repositorio IAEN"
    url: "https://rraae.cedia.edu.ec/Record/IAEN-"
    access: "Open"
    content: ["public_policy", "security_studies"]
    harvest:
      method: "aggregator"
      base_url: "https://rraae.cedia.edu.ec/oai"
      notes: "Filter by IAEN provider through RRAAE."
    storage:
      prefix: "iaen"

  - institution: "Universidad Técnica Estatal de Quevedo"
    short_code: "UTEQ"
    platform: "DSpace"
    repository: "Repositorio Digital UTEQ"
    url: "https://repositorio.uteq.edu.ec/"
    access: "Open"
    content: ["agriculture", "environmental_research"]
    harvest:
      method: "oai-pmh"
      base_url: "https://repositorio.uteq.edu.ec/oai/request"
      notes: "Apply domain tag 'agricultura'."
    storage:
      prefix: "uteq"

  - institution: "Universidad de las Fuerzas Armadas"
    short_code: "ESPE"
    platform: "DSpace"
    repository: "Repositorio Digital ESPE"
    url: "https://repositorio.espe.edu.ec/"
    access: "Open"
    content: ["military_sciences", "engineering", "administration"]
    harvest:
      method: "oai-pmh"
      base_url: "https://repositorio.espe.edu.ec/oai/request"
      notes: "Mask personal data in acknowledgements where needed."
    storage:
      prefix: "espe"

  - institution: "Universidad Regional Amazónica IKIAM"
    short_code: "IKIAM"
    platform: "DSpace"
    repository: "Repositorio Digital IKIAM"
    url: "https://repositorio.ikiam.edu.ec/"
    access: "Open"
    content: ["biodiversity", "earth_sciences", "nanotechnology"]
    harvest:
      method: "oai-pmh"
      base_url: "https://repositorio.ikiam.edu.ec/oai/request"
      notes: "Capture geospatial metadata when present."
    storage:
      prefix: "ikiam"

  - institution: "Universidad Estatal Amazónica"
    short_code: "UEA"
    platform: "DSpace"
    repository: "Repositorio Digital UEA"
    url: "https://repositorio.uea.edu.ec/"
    access: "Open"
    content: ["forestry", "ecotourism", "agriculture"]
    harvest:
      method: "oai-pmh"
      base_url: "https://repositorio.uea.edu.ec/oai/request"
      notes: "Account for intermittent downtime; enable resume."
    storage:
      prefix: "uea"

  - institution: "Universidad Laica Eloy Alfaro de Manabí"
    short_code: "ULEAM"
    platform: "DSpace"
    repository: "Repositorio Digital ULEAM"
    url: "https://repositorio.uleam.edu.ec/"
    access: "Open"
    content: ["thesis", "coastal_research", "marine_studies"]
    harvest:
      method: "oai-pmh"
      base_url: "https://repositorio.uleam.edu.ec/oai/request"
      notes: "Normalize subject headings with controlled vocabulary."
    storage:
      prefix: "uleam"

aggregators:
  - name: "RRAAE"
    url: "https://rraae.cedia.edu.ec/vufind/"
    harvest:
      method: "oai-pmh"
      base_url: "https://rraae.cedia.edu.ec/oai"
      notes: "Use provider filter; avoid double-counting records already harvested directly."

  - name: "ROA"
    url: "https://roa.cedia.edu.ec/"
    harvest:
      method: "scrapy"
      entrypoint: "https://roa.cedia.edu.ec/items-browse"
      notes: "Collect metadata only; media files typically CC-BY."

  - name: "Portal Bibliotecas del Ecuador"
    url: "https://www.bibliotecasdelecuador.com/"
    harvest:
      method: "selenium"
      entrypoint: "https://www.bibliotecasdelecuador.com/bibliotecas/"
      notes: "Acts as search index; capture links for targeted crawls rather than bulk download."
